version: '2'
services:
  server:
    image: atf-test
  client:
    image: atf-test
    command: -Durl=http://server:8080 ciaran.liedeman.client.ClientApplication
  random:
    image: atf-test
    command: java
    command: ciaran.liedeman.random.Random